// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbdlgxzcmijuadbkxene.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJiZGxneHpjbWlqdWFkYmt4ZW5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODE3MzIsImV4cCI6MjA2ODk1NzczMn0.87UfQoDmTHOkJxEyc6-Na3FMgOh01WxTQBBtuAaLDI4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});